### ISSUE TITLE
Add default profile picture in the dashboard

### ISSUE THREAD

**Issue by vedrecide** [Seniatical/Mecha-Karen#124]
Whenever somebody without a discord profile picture logs in, it appears that the image at the top right doesn't actually show giving it a weird look..

**Comment by Seniatical** [comment]
Should be patched in the next update

**Comment by Daftscientist** [comment]
Isa is dumby

**Comment by vedrecide** [comment]
TRUEEEEEEEEEEEEEE

**Comment by faluhub** [comment]
KEKW
